# Generated by Django 4.1 on 2023-04-18 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisement',
            name='user',
        ),
    ]
