# Generated by Django 4.1 on 2023-04-20 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='age',
        ),
    ]
